apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    texas.nais.io/enabled: "true"
  name: oebs-po-ap-api-q1
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  envFrom:
    - secret: oebs-po-ap-api-q1
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 11
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    requests:
      cpu: 40m
      memory: 512Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      
  accessPolicy:
    inbound:
      rules:
        - application: oebs-fullmakt-dev
        - application: tiltaksokonomi
          namespace: team-mulighetsrommet
          cluster: dev-gcp
    outbound:
      external:
        - host: mulighetsrommet-tiltaksokonomi.intern.dev.nav.no
      rules:
        - application: tiltaksokonomi
          namespace: team-mulighetsrommet
          cluster: dev-gcp

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-po-ap-api-q1.intern.dev.nav.no"
    - "https://oebs-po-ap-api-q1.dev-fss-pub.nais.io"