apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-po-ap-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 20
  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 4000m
      memory: 2048Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no

  accessPolicy:
    inbound:
      rules:
        - application: oebs-fullmakt-prod
        - application: tiltaksokonomi
          namespace: team-mulighetsrommet
          cluster: prod-gcp


  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: "kv/prod/fss/oebs-po-ap-api/team-oebs"
        mountPath: "/var/run/secrets/nais.io/vault"

  ingresses:
     - "https://oebs-po-ap-api.intern.nav.no"
     - "https://oebs-po-ap-api.prod-fss-pub.nais.io"
