
server:
  port: 8080

spring:
  profiles:
     active: nais
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

springdoc:
  packagesToScan: no.nav.oebs.po_ap.api
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha

shedlock:
  table-name: xxrtv_shedlock

nais-token-endpoint: ${NAIS_TOKEN_ENDPOINT}

# logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    root: warn
#    org.springframework.web: debug
#    org.hibernate: error